[features]
seeds = false
skip-lint = false

[programs.devnet]
program_deploy_process = "GUMmopTgVTwGEprNnwek1atmWTUMS1JwMB1HFC92eRNu"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
